### ISSUE TITLE
[BUG] Multiple instances of !=

### ISSUE THREAD

**Issue by adamretter** [eXist-db/existdb-saml#15]
The XQuery code contains multiple usages of the `!=` operator for string comparison. This is incorrect, instead:

1. For Atomic Values `$x ne $y` should be used
2. For Sequences `not($x = $y)` should be used

The `!=` operator rarely is the correct operator to use in XQuery, and almost always not what the developer intended.

**Comment by chakl** [comment]
@adamretter Thanks for your important bug reports!

I'm fully aware of this and have this scheduled for a code review. For now. it surprisingly does what the developer intended. There is no urgent need to fix this "bug", other than general code review.

**Comment by chakl** [comment]
closing

**Comment by adamretter** [comment]
I think we should leave this open until it's fixed. I'm happy to send a PR, I normally open issues before sending fixes in PRs
